ARG NODE_VERSION


FROM node:${NODE_VERSION}

WORKDIR /usr/src/app

COPY package.json ./
COPY tsconfig.json ./

COPY /packages/shared ./packages/shared
COPY /services/app ./services/app

RUN yarn

WORKDIR /usr/src/app/packages/shared
RUN yarn build

WORKDIR /usr/src/app/services/app
CMD ["yarn", "dev"]
