ARG NODE_VERSION


FROM node:${NODE_VERSION}

WORKDIR /usr/src/app

COPY package.json ./
COPY tsconfig.json ./

COPY /packages/shared ./packages/shared
COPY /services/client ./services/client

RUN yarn

WORKDIR /usr/src/app/packages/shared
RUN yarn build

WORKDIR /usr/src/app/services/client
CMD ["yarn", "dev"]
